name: build

on: [push, pull_request]

jobs:
  build-shared:
    runs-on:  ubuntu-18.04

    strategy:
      matrix:
        node: [ 14.2.0 ]
        build: [linux-x86-64, android-arm64]

    steps:
    - uses: actions/checkout@v2

    - name: Set Android NDK
      run: echo "::set-env name=ANDROID_NDK_HOME::$ANDROID_SDK_ROOT/ndk-bundle"
                       

    - name: Build
      run: ./build.sh build-${{matrix.build}} ${{matrix.node}}
    
    - uses: actions/upload-artifact@v2
      with:
        name: lib-${{matrix.build}}-${{matrix.node}}
        path: node/out/Release/lib.target
