name: build

on: [push, pull_request]

jobs:
  build-android_arm64:
    runs-on:  ubuntu-18.04
    
    env:
      TAG: 14.2.0

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk-bundle ./build.sh build_android_arm64 $TAG
    
    - uses: actions/download-artifact@v2
      with:
        name: shared-library
        path: node/out/Release/lib.target

  build-x86_64:
    runs-on:  ubuntu-18.04
    
    env:
      TAG: 14.2.0

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: ./build.sh build_x86_64
    
    - uses: actions/download-artifact@v2
      with:
        name: shared-library
        path: node/out/Release/lib.target
